version: "3.7"
services:

    db:
        image: mysql
        container_name: db_docker_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
        cap_add:
            - SYS_NICE

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_docker_symfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_docker_symfony
        ports:
            - "80:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./vesoul:/var/www/vesoul
        restart: always
        networks:
            - dev
        cap_add:
            - SYS_NICE

    node:
        image: node
        container_name: node_docker_symfony
        command: "yarn run watch"
        restart: always
        depends_on:
            - db
        working_dir: /home/node/app
        volumes:
            - ./vesoul:/home/node/app
        user: "node"
        environment:
            - NODE_ENV=production


networks:
    dev:

volumes:
    db-data:
